version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: athishulleri/demo:latest 
    container_name: miniproject-backend
    command: sh -c "chmod +x ./migrate.sh && chmod +x ./entrypoint.sh && sh ./migrate.sh && ./entrypoint.sh"
    ports:
      - 8000:8000
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=miniproject 